spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        query:
          in_clause_parameter_padding: true
    show-sql: true
server:
  error:
    include-stacktrace: never